backend:
  name: github
  repo: svetlana18011991/shkatulka-math
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Товары"
    file: "products.json"
    format: "json"
    create: true
    fields:
      - name: "items"
        label: "Список товаров"
        widget: "list"
        fields:
          - { name: "title", label: "Название товара", widget: "string" }
          - { name: "price", label: "Цена", widget: "number" }

          - { name: "description", label: "Описание", widget: "text", required: false }

          - name: "images"
            label: "Изображения"
            widget: "list"
            field: { name: "image", label: "Картинка", widget: "image" }
            required: false

          - { name: "video", label: "Видео (ссылка YouTube или mp4)", widget: "string", required: false }

          - { name: "category", label: "Категория", widget: "string", required: false }

          - { name: "tags", label: "Теги", widget: "list", required: false }
