backend:
  name: github
  repo: svetlana18011991/shkatulka-math
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "catalog"
    label: "Каталог материалов"
    folder: "products" # Теперь все товары лежат в папке products/
    create: true       # Появится кнопка "New"
    slug: "{{slug}}"   # Имя файла будет создаваться автоматически
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Категория / Класс", name: "grade", widget: "select", options: ["5", "6", "7", "8", "9", "10", "11", "oge", "ege", "free"] }
      - { label: "Цена", name: "price", widget: "number", value_type: "int" }
      - { label: "Описание", name: "description", widget: "text", required: false }
      - { label: "Что внутри", name: "inside", widget: "list", required: false }
      - { label: "Ссылка на оплату", name: "buyLink", widget: "string", required: false }
      - { label: "Главное фото", name: "image", widget: "image", required: false }
      - { label: "Файл", name: "downloadFile", widget: "file", required: false }
      - { label: "Теги", name: "tags", widget: "list", required: false }